name: Purge jsDelivr Cache

on:
  deployment_status

jobs:
  purge-cache:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/VickHub123/my-games@main/getdatatest/insano.txt
