name: Purge jsDelivr Cache

on:
  deployment_status:
    types: [completed]

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Repetir ate que o status seja true
        run: |
          STATUS_VALIDO="false"
          while [ "$STATUS_VALIDO" = "false" ]; do
            if [ "${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.deployment.ref == 'main' }}" = "true" ]; then
              STATUS_VALIDO="true"
            else
              sleep 5
            fi
          done
      
      - name: Purge jsDelivr
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/VickHub123/my-games@main/getdatatest/insano.txt
